# Generated by Django 5.2.9 on 2025-12-05 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, help_text='Prozentsatz, z.B. 7.70', max_digits=5)),
                ('name', models.CharField(help_text='z.B. MwSt. Standard', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ean', models.CharField(help_text='Barcode / EAN', max_length=13, unique=True)),
                ('sku', models.CharField(blank=True, help_text='Interne Artikelnummer', max_length=50, unique=True)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('stock_quantity', models.IntegerField(default=0)),
                ('unit', models.CharField(choices=[('PCS', 'Stück'), ('KG', 'Kilogramm'), ('L', 'Liter')], default='PCS', max_length=3)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einkaufspreis (Netto)')),
                ('sales_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Verkaufspreis (Brutto)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.category')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.supplier')),
                ('vat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vat')),
            ],
        ),
    ]
