# Generated by Django 5.2.9 on 2025-12-05 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vat',
            name='rate',
            field=models.DecimalField(decimal_places=2, help_text='Prozentsatz, z.B. 19.00', max_digits=5),
        ),
    ]
