# Generated by Django 5.2.9 on 2025-12-09 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vat_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sku_prefix',
            field=models.PositiveIntegerField(editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktiv'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert (z.B. 10001)', max_length=50, unique=True),
        ),
    ]
