# Generated by Django 5.2.9 on 2025-12-09 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0003_category_sku_prefix_product_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Veränderung des Bestands (positiv oder negativ)')),
                ('stock_after', models.IntegerField(help_text='Bestand nach der Bewegung')),
                ('movement_type', models.CharField(choices=[('INITIAL', 'Initialbestand'), ('PURCHASE', 'Wareneingang'), ('SALE', 'Verkauf'), ('CORRECTION', 'Manuelle Korrektur'), ('RETURN', 'Retoure'), ('DAMAGED', 'Bruch/Verlust')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lagerbewegung',
                'verbose_name_plural': 'Lagerbewegungen',
                'ordering': ['-created_at'],
            },
        ),
    ]
