# Generated by Django 5.2.9 on 2025-12-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_stockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Deaktivieren für Dienstleistungen oder Gastronomie-Produkte (z.B. Kaffee).', verbose_name='Lagerbestand führen'),
        ),
    ]
