# Generated by Django 5.2.9 on 2025-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_track_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ean',
            field=models.CharField(blank=True, help_text='Wird automatisch generiert, falls leer (Barcode / EAN)', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='track_stock',
            field=models.BooleanField(default=True, help_text='Deaktivieren für Dienstleistungen', verbose_name='Lagerbestand führen'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Veränderung des Bestands'),
        ),
    ]
