# Generated by Django 5.2.9 on 2026-07-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_stockkeeper_mitarbeiterin_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_group',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Artikel mit gleichem Wert werden im Shop zu einem Produkt zusammengefasst (leer = eigenständiges Produkt).', max_length=140, verbose_name='Varianten-Gruppe'),
        ),
    ]
