# Generated by Django 5.2.9 on 2026-07-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_product_variant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pickup_only',
            field=models.BooleanField(default=False, help_text='Für diese Kategorie im Webshop keinen Versand erlauben (z.B. wenn eine Ausmessung im Laden nötig ist).', verbose_name='Nur Abholung im Laden'),
        ),
        migrations.AddField(
            model_name='category',
            name='store_notice',
            field=models.TextField(blank=True, default='', help_text='Hinweis, der im Shop bei allen Produkten dieser Kategorie erscheint.', verbose_name='Webshop-Kundenhinweis'),
        ),
    ]
