# Generated by Django 5.2.9 on 2025-12-05 22:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='MwSt Satz zum Zeitpunkt des Kaufs (z.B. 8.10)', max_digits=5),
        ),
    ]
