# Generated by Django 5.2.9 on 2025-12-05 23:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_purchaseorderitem_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saleitem',
            name='unit_price_gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True),
        ),
    ]
