# Generated by Django 5.2.9 on 2025-12-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_sale_created_by_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Barzahlung'), ('SUMUP', 'SumUp (Karte)'), ('TWINT', 'Twint')], default='CASH', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_id',
            field=models.CharField(blank=True, help_text='Transaktions-ID von SumUp/Twint', max_length=100, null=True),
        ),
    ]
