# Generated by Django 5.2.9 on 2025-12-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_sale_payment_method_sale_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('POS', 'Ladenlokal (Kasse)'), ('WEB', 'Online Shop (Shopify)'), ('MANUAL', 'Manuell / Telefon')], default='POS', help_text='Über welchen Kanal wurde dieser Verkauf getätigt?', max_length=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Barzahlung'), ('SUMUP', 'SumUp (Karte)'), ('SHOPIFY', 'Shopify Payments'), ('TWINT', 'Twint'), ('INVOICE', 'Rechnung')], default='CASH', max_length=20),
        ),
    ]
