# Generated by Django 5.2.9 on 2025-12-12 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_sale_channel_alter_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'Abgeschlossen'), ('REFUNDED', 'Storniert / Retourniert')], default='COMPLETED', max_length=20),
        ),
    ]
