# Generated by Django 5.2.9 on 2026-04-19 09:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='idempotency_key',
            field=models.CharField(blank=True, db_index=True, help_text='Client-generierter Key, verhindert Doppelbuchungen durch Retries/Doppelklicks', max_length=64, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_id__isnull', False), models.Q(('transaction_id', ''), _negated=True), ('status', 'COMPLETED')), fields=('transaction_id',), name='unique_tx_id_when_completed'),
        ),
    ]
