# Generated by Django 5.2.9 on 2026-05-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_sale_idempotency_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_address',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_zip_code',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_last_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='invoice_status',
            field=models.CharField(choices=[('NA', 'Nicht anwendbar'), ('SENT', 'Versendet'), ('FAILED', 'Versand fehlgeschlagen'), ('RESENT', 'Erneut versendet')], default='NA', max_length=10),
        ),
    ]
