# Generated by Django 5.2.9 on 2026-07-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_sale_customer_address_sale_customer_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Barzahlung'), ('SUMUP', 'SumUp (Karte)'), ('SHOPIFY', 'Shopify Payments'), ('TWINT', 'Twint'), ('INVOICE', 'Rechnung'), ('PAYREXX', 'Payrexx (Webshop online)')], default='CASH', max_length=20),
        ),
    ]
