# Generated by Django 5.2.9 on 2026-03-29 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0007_sale_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SumUpPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_credit_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Gutschrift auf Bankkonto (CHF)')),
                ('bank_credit_date', models.DateField(verbose_name='Datum Bankgutschrift')),
                ('sumup_payout_id', models.CharField(blank=True, max_length=100)),
                ('period_start', models.DateField(blank=True, null=True, verbose_name='Abrechnungsperiode von')),
                ('period_end', models.DateField(blank=True, null=True, verbose_name='Abrechnungsperiode bis')),
                ('sumup_gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SumUp Bruttoumsatz (vor Gebühren)')),
                ('sumup_fees_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SumUp Gebühren')),
                ('sumup_net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='SumUp Nettobetrag (= Bankgutschrift)')),
                ('status', models.CharField(choices=[('DRAFT', 'Entwurf'), ('IN_REVIEW', 'In Prüfung'), ('COMPLETED', 'Abgeschlossen')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SumUp Auszahlung',
                'verbose_name_plural': 'SumUp Auszahlungen',
                'ordering': ['-bank_credit_date'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sk_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sk_timestamp', models.DateTimeField(blank=True, null=True)),
                ('sumup_tx_id', models.CharField(blank=True, max_length=100)),
                ('sumup_tx_code', models.CharField(blank=True, max_length=100)),
                ('sumup_foreign_tx_id', models.CharField(blank=True, help_text='= Sale.id, falls beim Checkout übergeben', max_length=128)),
                ('sumup_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sumup_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('sumup_timestamp', models.DateTimeField(blank=True, null=True)),
                ('match_tier', models.CharField(blank=True, choices=[('EXACT', 'Exakt (foreign_tx_id)'), ('AMOUNT_TIME', 'Betrag + Zeit (±2min)'), ('AMOUNT_DATE', 'Betrag + Tag'), ('NO_MATCH', 'Kein Match')], max_length=20)),
                ('match_status', models.CharField(choices=[('MATCHED', 'Abgeglichen'), ('ONLY_SUMUP', 'Nur SumUp (fehlt in SK)'), ('ONLY_SK', 'Nur SK (falscher Zahlungstyp?)'), ('GAP', 'Betragsdifferenz > Toleranz')], max_length=20)),
                ('gap_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('gap_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('channel', models.CharField(choices=[('LADEN', 'Laden (Supportelle)'), ('CAFE', 'Café'), ('UNKNOWN', 'Unbekannt')], default='UNKNOWN', max_length=10)),
                ('resolution', models.CharField(choices=[('PENDING', 'Ausstehend'), ('ACCEPTED', 'Akzeptiert'), ('PAYMENT_TYPE_CHANGED', 'Zahlungsart korrigiert'), ('SALE_ADDED', 'In SK nacherfasst'), ('MANUAL', 'Manuell bearbeitet'), ('IGNORED', 'Ignoriert')], default='PENDING', max_length=30)),
                ('resolution_note', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.sale')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reconciliation.sumuppayout')),
            ],
            options={
                'ordering': ['sumup_timestamp', 'sk_timestamp'],
            },
        ),
    ]
