# Generated by Django 5.2.9 on 2026-03-29 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconciliationitem',
            name='resolution',
            field=models.CharField(choices=[('PENDING', 'Ausstehend'), ('ACCEPTED', 'Akzeptiert'), ('PAYMENT_TYPE_CHANGED', 'Zahlungsart korrigiert'), ('SALE_DELETED', 'Sale gelöscht/storniert'), ('SALE_ADDED', 'In SK nacherfasst'), ('MANUAL', 'Manuell bearbeitet'), ('IGNORED', 'Ignoriert')], default='PENDING', max_length=30),
        ),
    ]
