# Generated by Django 5.2.9 on 2026-06-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_alter_reconciliationitem_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationitem',
            name='sumup_refund_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Refund-Abzug auf dieser Auszahlungszeile (nicht erstattete Gebühr einer Rückerstattung)', max_digits=10),
        ),
    ]
