"""
Django settings for stock_keeper project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dsq#u+gn6v-24bcgf-0$0ddi(+$g^p7hz33qzzjz22s*_@k*1w'


# Application definition

INSTALLED_APPS = [
    # custom admin ui
    'jazzmin',
    
    #django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Eigene Apps
    'core',
    'commerce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_keeper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_keeper.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# NEU HINZUGEFÜGT: Der Speicherort, an den collectstatic kopiert
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Media Files (Uploads von Usern/Produkten)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN REDIRECT (Wichtig!)
LOGIN_REDIRECT_URL = '/'          # Nach Login zum Custom Dashboard
LOGOUT_REDIRECT_URL = '/admin/login/' # Nach Logout zum Login


# --- JAZZMIN KONFIGURATION ---
JAZZMIN_SETTINGS = {
    "site_title": "Stock Keeper",
    "site_header": "Stock Keeper",
    "site_brand": "SupportElle", # Text neben dem Logo (oder leer lassen)
    "welcome_sign": "Willkommen im Lager",
    "copyright": "Mileja GmbH",
    "search_model": ["core.Product"],

    # --- LOGO KONFIGURATION (NEU) ---
    # --- CUSTOM CSS ---
    # Pfad relativ zu static/ (also core/static/css/custom_admin.css -> css/custom_admin.css)
    "custom_css": "css/custom_admin.css",
    # Pfad relativ zu Ihrem static-Ordner (also static/img/logo.png)
    "site_logo": "img/bee_stock_keeper_logo.png",
    
    # Logo auf dem Login-Screen (kann das gleiche oder ein größeres sein)
    "login_logo": "img/bee_stock_keeper_logo_login.png",
    
    # Favicon (Browser Tab)
    "site_icon": "img/bee_stock_keeper_logo.png",
    
    # CSS Klassen für das Logo (optional)
    "site_logo_classes": "img-circle", 

    "show_ui_builder": True,

    # --- MODELLE VERSTECKEN ---
    "hide_models": [
        "commerce.PurchaseOrder", 
        "commerce.Sale",
        "core.Product",
        "core.Category", 
        "core.Supplier",
        "core.Vat"
    ],

    # --- SIDEBAR MENU (LINKS) ---
    "custom_links": {
        "commerce": [
            # 0. COCKPIT
            {"name": "Cockpit", "url": "home", "icon": "fas fa-tachometer-alt", "permissions": ["auth.view_user"]},

            # 1. OPERATIV
            {"name": "Kasse (POS)", "url": "pos", "icon": "fas fa-cash-register text-success", "permissions": ["auth.view_user"]},
            {"name": "Bestellung erfassen", "url": "purchase_pos", "icon": "fas fa-truck-loading text-primary", "permissions": ["auth.view_user"]},
            
            # 2. VERWALTUNG
            {"name": "Verkäufe (Sales)", "url": "admin:commerce_sale_changelist", "icon": "fas fa-shopping-basket", "permissions": ["commerce.view_sale"]},
            {"name": "Bestellarchiv", "url": "admin:commerce_purchaseorder_changelist", "icon": "fas fa-file-invoice", "permissions": ["commerce.view_purchaseorder"]},
            
            # 3. REPORTING (NEU)
            {"name": "Umsatzliste (PDF)", "url": "accounting_report", "icon": "fas fa-chart-line text-info", "permissions": ["auth.view_user"]},
            {"name": "Scan-Liste (PDF)", "url": "ean_labels", "icon": "fas fa-barcode text-info", "permissions": ["auth.view_user"]},
        ],
        
        "core": [
            # 1. OPERATIV
            {"name": "Lagerverwaltung", "url": "/core/scanner/", "icon": "fas fa-qrcode text-warning", "permissions": ["auth.view_user"]},
            
            # 2. STAMMDATEN
            {"name": "Produkte", "url": "admin:core_product_changelist", "icon": "fas fa-box-open", "permissions": ["core.view_product"]},
            {"name": "Kategorien", "url": "admin:core_category_changelist", "icon": "fas fa-tags", "permissions": ["core.view_category"]},
            {"name": "Lieferanten", "url": "admin:core_supplier_changelist", "icon": "fas fa-truck", "permissions": ["core.view_supplier"]},
            {"name": "Steuersätze", "url": "admin:core_vat_changelist", "icon": "fas fa-percent", "permissions": ["core.view_vat"]},
        ]
    },

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
    },
    
    "order_with_respect_to": [
        "commerce", 
        "core",     
        "auth"      
    ],
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}