"""
Django settings for stock_keeper project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dsq#u+gn6v-24bcgf-0$0ddi(+$g^p7hz33qzzjz22s*_@k*1w'


# Application definition

INSTALLED_APPS = [
    # custom admin ui
    'jazzmin',
    
    #django default apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Eigene Apps
    'core',
    'commerce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'stock_keeper.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'stock_keeper.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
# NEU HINZUGEFÜGT: Der Speicherort, an den collectstatic kopiert
STATIC_ROOT = BASE_DIR / 'staticfiles' 

# Media Files (Uploads von Usern/Produkten)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# LOGIN REDIRECT (Wichtig!)
LOGIN_REDIRECT_URL = '/'          # Nach Login zum Custom Dashboard
LOGOUT_REDIRECT_URL = '/admin/login/' # Nach Logout zum Login


# --- JAZZMIN KONFIGURATION ---
JAZZMIN_SETTINGS = {
    "site_title": "Stock Keeper",
    "site_header": "Stock Keeper",
    "site_brand": "Stock Keeper",
    "welcome_sign": "Willkommen im Lager",
    "copyright": "Stock Keeper Ltd",
    "search_model": ["core.Product"],

    "show_ui_builder": True,

    # --- TOP MENU (OBEN) ---
    # Hier nur noch das absolute Minimum.
    # Da das Logo links oft zur Admin-Übersicht führt, setzen wir hier unser Chart-Dashboard.
    "topmenu_links": [
        {"name": "Cockpit", "url": "home", "permissions": ["auth.view_user"]},
    ],

    # --- SIDEBAR MENU (LINKS) ---
    # Hier kommen die operativen Hauptfunktionen hin.
    "custom_links": {
        # Wir gruppieren ALLES "Operative" unter Commerce
        "commerce": [
            # 1. Verkauf
            {"name": "Kasse (POS)", "url": "pos", "icon": "fas fa-cash-register text-success", "permissions": ["auth.view_user"]},
            # 2. Einkauf
            {"name": "Bestellung erfassen", "url": "purchase_pos", "icon": "fas fa-truck-loading text-primary", "permissions": ["auth.view_user"]},
            # 3. Lager (Scanner hierhin verschoben und umbenannt)
            {"name": "Lagerverwaltung", "url": "/core/scanner/", "icon": "fas fa-qrcode text-warning", "permissions": ["auth.view_user"]},
        ],
        # Core hat keine Custom Links mehr, nur noch die Modelle (Stammdaten)
    },

    # Icons für Apps und Modelle
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        
        "core.Product": "fas fa-box-open",
        "core.Category": "fas fa-tags",
        "core.Supplier": "fas fa-truck",
        "core.Vat": "fas fa-percent",
        
        "commerce.PurchaseOrder": "fas fa-file-invoice",
        "commerce.Sale": "fas fa-shopping-basket",
    },
    
    # Reihenfolge: Commerce (Tagesgeschäft) vor Core (Stammdaten)
    "order_with_respect_to": [
        "commerce", # POS, Bestellungen
        "core",     # Produkte, Scanner
        "auth"      # Benutzerverwaltung
    ],
    
    # Optional: Apps einklappen, um Platz zu sparen?
    # "navigation_expanded": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-primary",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}